### ISSUE TITLE
Issues, Peer to Peer Review 04/13/2023 Morning session

### ISSUE THREAD

**Issue by misalazeem** [kifle23/Portfolio#16]
Good job you did well 👍 👍 

kindly change the font size of the card heading to match with the Figma design. 😱 
Apart from that, the recent works section is displayed in either grid or flex. Kindly align the picture and the text. 😱 

Other than that great job with the project Kifle. 🦄 🦄

**Comment by kifle23** [comment]
Thank you, guys! I am working on it
